# Generated by Django 6.0.4 on 2026-04-07 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='offline', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
